### ISSUE TITLE
Invisible Power not working properly on beta branch

### ISSUE THREAD

**Issue by lobbienjonsji** [kiooeht/StSLib#20]
On the current Beta Branch the invisible powers are still invisible, but when hovering over the player character still show power tips.

**Comment by godinj** [comment]
Any update on this?

**Comment by kiooeht** [comment]
This was fixed (https://github.com/kiooeht/StSLib/commit/95070a20416e902fd382e00833827c3f38bba39e) but I forgot to close the issue.
